stages:
  - test
  - build
  - deploy

execute:test:
  image: python:latest
  stage: test
  tags:
    - docker
  script: 
    - python test.py


build:image:
  stage: build
  tags:
    - ssh
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  tags:
    - ssh
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "Deploy image $IMAGE_TAG"
    - docker rm -f $CI_PROJECT_NAME 
    - docker run -p 80:5000 -d --name $CI_PROJECT_NAME $IMAGE_TAG

